version: "3.9"

services:

    # Web Server
    web:
        build:
            context: ./server
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server/resume:/app
        ports:
            - "8000:8000"
        container_name: web-serv

